train: []
inference:
  - _target_: src.metrics.MOSNet
    name: "MOS"
  - _target_: src.metrics.ScaleInvariantSignalToDistortionRatio
    name: "SISDR"
  - _target_: src.metrics.SignalToNoiseRatio
    name: "SNR"
  # - _target_: src.metrics.VGGDistance
  #   name: "VGG_dist"
  - _target_: src.metrics.LSD
    name: "LSD"
  - _target_: src.metrics.LSD_LF
    name: "LSD_LF"
  - _target_: src.metrics.LSD_HF
    name: "LSD_HF"
  - _target_: src.metrics.STOI
    name: "STOI"
  - _target_: src.metrics.PESQ
    name: "PESQ"
  - _target_: src.metrics.CSIG
    name: "CSIG"
  - _target_: src.metrics.CBAK
    name: "CBAK"
  - _target_: src.metrics.COVL
    name: "COVL"