_target_: src.logger.WandBWriter
project_name: "hifi_plus_plus"
entity: null
run_name: "test_specunet"
mode: "online"
loss_names: ["gen_loss_8_16", "disc_loss_8_16", "mpd_gen_loss_8_16", "msd_gen_loss_8_16", "mel_spec_loss_8_16", "mpd_feats_gen_loss_8_16", "msd_feats_gen_loss_8_16", "mpd_disc_loss_8_16", "msd_disc_loss_8_16", "gen_loss_4_8", "disc_loss_4_8", "mpd_gen_loss_4_8", "msd_gen_loss_4_8", "mel_spec_loss_4_8", "mpd_feats_gen_loss_4_8", "msd_feats_gen_loss_4_8", "mpd_disc_loss_4_8", "msd_disc_loss_4_8"]
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8 # length of the run_id
